export const orderEvents = {
    ORDER_ADD_PENDING: "ORDER_ADD_PENDING",
    ORDER_ADD_FAILED: "ORDER_ADD_FAILED",
    ORDER_ADD_FINISHED: "ORDER_ADD_FINISHED",
    ORDER_ADD_CHANGE_PAYMENT_DATE_FINISHED: "ORDER_ADD_CHANGE_PAYMENT_DATE_FINISHED"
  };
  